# Streamlit secrets configuration
# Add your API keys here - DO NOT commit this file to version control

# OpenAI API Key
OPENAI_API_KEY = "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"

# Google AI (Gemini) API Key
GOOGLE_API_KEY = "AIzaSyDRrjQ3vMG4aX_0Z-AUEEs9aApVLgE5IAg"

# Ollama endpoint (if using local Ollama)
OLLAMA_ENDPOINT = "http://localhost:11434"

# Additional secrets (if needed)
# ANTHROPIC_API_KEY = "your-anthropic-api-key-here"
# HUGGINGFACE_API_KEY = "your-huggingface-api-key-here"
